name: Sync to GitLab

on:
  push:
    branches:
      - main  # Ganti kalau kamu pakai branch lain

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <--- penting! biar nggak shallow clone

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "sync@github"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/xdx57/wbtc.git
          git push gitlab --all
          git push gitlab --tags

